name: SSE CI/CD

on: [push]

jobs:
  style_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: "Install style checker"
        run: pip install black
      - name: 'Run style check'
        run: black --check .
  test:
    runs-on: ubuntu-latest
    needs: style_check
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: 'Install python test package'
        run: pip install pytest
      - name: 'Install code coverage testing package'
        run: pip install coverage
      - name: 'Install python code dependencies'
        run: pip install numpy matplotlib
      - name: 'Run coverage test'
        run: coverage run -m pytest
      - name: 'Upload .coverage'
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: .coverage
          retention-days: 1
  coverage_report:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: 'Install python test package'
        run: pip install pytest
      - name: 'Install code coverage testing package'
        run: pip install coverage
      - name: 'Download artifact'
        uses: actions/download-artifact@v2
        with:
          name: coverage-report
      - name: 'Create coverage report in terminal'
        run: coverage report
      - name: 'Convert coverage info into XML'
        run: coverage xml
      - name: 'Upload coverage.xml'
        uses: actions/upload-artifact@v2
        with:
          name: 'coverage-xml'
          path: 'coverage.xml'
          retention-days: 14
 
